### PR TITLE
Vendorise and use stable version of framework

### PR DESCRIPTION
**Pull request by riddler7**
Updated to use silverstripe-vendormodule and removed dev for framework version.

### CODE REVIEW

**Comment by robbieaverill** [comment]
Thanks! I think we need to update the Travis config to reflect the vendor location too

**Comment by riddler7** [comment]
Yeah, saw that, just testing on another repo and will update when I have it working.

**Review by robbieaverill — CHANGES_REQUESTED** [review]
Thanks! Could you please remove the composer.lock? Otherwise this looks good

**Comment by riddler7** [comment]
Scrutinizer was failing without the lock file. Looks like I've finally got it figured out, adding stability to composer.json sorted it.

**Review by robbieaverill — APPROVED** [review]

**Pull request merged**
